import "./globals.css";
import {Inter} from "next/font/google";
import ReactQueryProvider from "@/utils/provider";
import LogoutButton from "@/components/LogoutButton";
import Header from "@/components/Header";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "TODO APP",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <div id="wrapper">
            <Header />
            {children}
            <LogoutButton />
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
